services:
  dash-app:
    image: "romain894/src-dash-app"
    ports:
      - "127.0.0.1:8050:8050"
    env_file:
      - docker_var.env
    environment:
      - FLASK_APP=main_app
    depends_on:
      - redis
    volumes:
      - "./openalex-data:/usr/src/app/data"
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        #max_attempts: 3
        window: 30s
      resources:
        limits:
          cpus: '3'
          memory: 30G


  celery-worker:
    image: "romain894/src-dash-app"
    command: /start_celery_worker.sh
    env_file:
      - docker_var.env
    environment:
      - FLASK_APP=main_app
    depends_on:
      - redis
    volumes:
      - "./openalex-data:/usr/src/app/data"
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        #max_attempts: 3
        window: 30s
      resources:
        limits:
          cpus: '2'
          #memory: 30G


  redis: 
    image: redislabs/redismod
    volumes:
      - "./redis.conf:/usr/local/etc/redis/redis.conf"
    ports:
      - "127.0.0.1:6379:6379"
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        #max_attempts: 3
        window: 30s
      resources:
        limits:
          cpus: '2'
          # memory: 10G # limited in redis.conf # use x2 max redis conf memory when backing up

